---
title: "Taller 2.2 Introducción a Matrices"
author: "Nombre"
date: "2023-02-09"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---

# 1. Operaciones matriciales básicas

## 1.1 Producto matricial

Este ejercicio incluye una demostración al final.

```{r, message=FALSE, warning=FALSE}
# Ejercicio 1
# A (2,1,1,3)
# B (1,4,2,5,0,3)
# Calcular: (1) B'.A' (2) (A.B)' (3) Demostrar que B'.A' = (A'.B')

# R./
A =       # Matriz A
B =       # Matriz B

A
B

# (1) B'.A'
    # %*%  representa el producto matricial, 
               # "t" corresponde a la transpuesta de una matriz

# (2) (A.B)'


# (3) B'.A' = (A.B)'
   # Demostración


```

## 1.2 Determinantes

Se calculará la determinante de dos matrices cuadradas

```{r, message=FALSE, warning=FALSE}
#-------------
# Ejercicio 2
# A (2,3,3,2)
# B (1,4,2,5,0,3)
# Cacular: Determinante de A y de B

#R./
A = 
B = 

A     
B

# Determinantes



```


## 1.3 Matriz inversa

Cálculo de una matriz inversa (A)-1


